import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <Toaster
  position="top-center"
  reverseOrder={false}
  containerStyle={{
    top: 85, // Navbar-এর ঠিক নিচে সুন্দরভাবে পজিশন করার জন্য
  }}
  toastOptions={{
    // ডিফল্ট স্টাইল (Navbar-এর সাথে ম্যাচিং গ্লাস ইফেক্ট)
    style: {
      background: "rgba(255, 255, 255, 0.85)", // Light Glass Effect
      color: "#0f172a", // Slate-900 Text
      borderRadius: "16px",
      padding: "12px 20px",
      fontSize: "14px",
      fontWeight: "600",
      backdropFilter: "blur(16px)", // Backdrop blur
      border: "1px solid rgba(226, 232, 240, 0.8)", // Light Border
      boxShadow: "0 20px 25px -5px rgba(147, 51, 234, 0.12), 0 8px 10px -6px rgba(147, 51, 234, 0.08)",
    },
    // Success Toast (Navbar Gradient + Emerald touch)
    success: {
      duration: 4000,
      iconTheme: {
        primary: "#a855f7", // Navbar Purple Color
        secondary: "#ffffff",
      },
      style: {
        background: "rgba(255, 255, 255, 0.9)",
        color: "#6b21a8", // Purple-800
        border: "1px solid rgba(192, 132, 252, 0.4)", // Light Purple Border
        boxShadow: "0 10px 25px -5px rgba(168, 85, 247, 0.25)",
      },
    },
  
    error: {
      duration: 4000,
      iconTheme: {
        primary: "#ef4444",
        secondary: "#ffffff",
      },
      style: {
        background: "rgba(255, 255, 255, 0.9)",
        color: "#991b1b", // Red-800
        border: "1px solid rgba(248, 113, 113, 0.4)",
        boxShadow: "0 10px 25px -5px rgba(239, 68, 68, 0.2)",
      },
    },
  }}
/>
        {children}
        </body>
    </html>
  );
}
